version: "3.7"

x-back: &back
  #image: ggpa/php:8.0.0-debug
  image: ggpa/php:8.0.2-rr-debug
  #image: ggpa/php:8.0.0-rr
  restart: unless-stopped
  volumes:
    - ./:/var/www
    - ./var/storage:/var/www/public/storage
    - ../../packages:/var/packages
    #- ./config/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    #- ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    #- ./config/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
    #- $BACKEND_ENV:/var/www/.env
  #env_file:
  #  - ./.env
  #depends_on:
  #  - mysql

services:
  back:
    <<: *back
    ports:
      - "$LISTEN_PORT:8080"
    environment:
      PHP_IDE_CONFIG: $PHP_IDE_CONFIG
  back-cli:
    image: ggpa/php:8.0.2-cli-debug
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./var/storage:/var/www/public/storage
      - ../../packages:/var/packages
    command: "/bin/sh -c 'while true; do sleep 60; done'"
    environment:
      PHP_IDE_CONFIG: $PHP_IDE_CONFIG
    #command: "sleep 600"
    #command: "/bin/sh -c 'rr -c ./.rr.yaml serve -d -v'"

    #  XDEBUG_MODE: debug
      # ,profile,trace,gcstats
    #  XDEBUG_CONFIG: "client_host=host.docker.internal idekey=PHPSTORM discover_client_host=1 start_with_request=yes"
  #back_queue:
  #  <<: *back
  #  env_file:
  #    - ./.env
  #  command: "/bin/sh -c 'php artisan queue:work --verbose --tries=3 --timeout=90'"
  #back_shedule:
  #  <<: *back
  #  env_file:
  #    - ./.env
  #  command: "/bin/sh -c 'while php /var/www/artisan schedule:run --verbose --no-interaction & do sleep 60; done'"
    # maybe work in laravel 8
    #command: "/bin/sh -c 'php artisan schedule:work'"

  #nginx:
  #  image: nginx:1.19.6-alpine
  #  restart: unless-stopped
  #  ports:
  #    - "$NGINX_PORT:80"
  #  volumes:
  #    - $BACKEND_PATH:/var/www
  #    - $HOST_STORAGE_PATH:/var/www/public/storage
  #    - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
  #  depends_on:
  #    - back

  #mysql:
  #  image: mysql:8.0
  #  restart: unless-stopped
  #  command: --default-authentication-plugin=mysql_native_password --secure_file_priv=NULL --general_log=0 --default-time-zone='+03:00'
  #  ports:
  #    - "27466:3306"
  #  volumes:
  #    #- ./config/mysql.conf:/etc/mysql/my.cnf:ro
  #    - ./mysql_data:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  #    MYSQL_DATABASE: $MYSQL_DATABASE
  #    MYSQL_USER: $MYSQL_USER
  #    MYSQL_PASSWORD: $MYSQL_PASSWORD
